In [139]:
## Importing Packages

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score
import pickle

[nltk_data] Downloading package punkt to /Users/ayaz/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/ayaz/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [140]:
## Reading the data

data = pd.read_csv("spam.csv", encoding="ISO-8859-1")

In [141]:
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

## Data Cleaning 

In [142]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [143]:
## Removing last 3 columns as the values are less 

data = data.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'])

In [144]:
data.rename(columns={'v1':'target', 'v2':'text'}, inplace=True)
data.sample(5)

target                                               text
1514    ham                       K:)all the best:)congrats...
4803    ham  Er, hello, things didn‰Û÷t quite go to plan ‰Û...
1517   spam  Our brand new mobile music service is now live...
568     ham  Love it! Daddy will make you scream with pleas...
4793    ham        Sorry that was my uncle. I.ll keep in touch

In [145]:
### Encoding the target values - ham to 0 and Spam to 1

encoder = LabelEncoder()
data['target'] = encoder.fit_transform(data['target'])

In [146]:
data

target                                               text
0          0  Go until jurong point, crazy.. Available only ...
1          0                      Ok lar... Joking wif u oni...
2          1  Free entry in 2 a wkly comp to win FA Cup fina...
3          0  U dun say so early hor... U c already then say...
4          0  Nah I don't think he goes to usf, he lives aro...
...      ...                                                ...
5567       1  This is the 2nd time we have tried 2 contact u...
5568       0              Will Ì_ b going to esplanade fr home?
5569       0  Pity, * was in mood for that. So...any other s...
5570       0  The guy did some bitching but I acted like i'd...
5571       0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [147]:
## Preprocessing 
# - Checking for missing values
# - Checking for duplicates and keeping only one

def preprocess(data):
    print("Null Values: ", data.isnull().sum())
    data = data.drop_duplicates(keep='first')
    print("Duplicate data: ", data.duplicated().sum())
    print("Shape : ", data.shape)
    print("Target Variable Value Count:", data['target'].value_counts())
    
preprocess(data)

Null Values:  target    0
text      0
dtype: int64
Duplicate data:  0
Shape :  (5169, 2)
Target Variable Value Count: 0    4516
1     653
Name: target, dtype: int64


In [148]:
data['num_characters'] = data['text'].apply(len)

In [149]:
data['num_of_words'] = data['text'].apply(lambda x: len(nltk.word_tokenize(x)))

In [150]:
data['num_of_sentences'] = data['text'].apply(lambda x: len(nltk.sent_tokenize(x)))

In [151]:
data.head()

target                                               text  num_characters  \
0       0  Go until jurong point, crazy.. Available only ...             111   
1       0                      Ok lar... Joking wif u oni...              29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...             155   
3       0  U dun say so early hor... U c already then say...              49   
4       0  Nah I don't think he goes to usf, he lives aro...              61   

   num_of_words  num_of_sentences  
0            24                 2  
1             8                 2  
2            37                 2  
3            13                 1  
4            15                 1

In [152]:
data

target                                               text  \
0          0  Go until jurong point, crazy.. Available only ...   
1          0                      Ok lar... Joking wif u oni...   
2          1  Free entry in 2 a wkly comp to win FA Cup fina...   
3          0  U dun say so early hor... U c already then say...   
4          0  Nah I don't think he goes to usf, he lives aro...   
...      ...                                                ...   
5567       1  This is the 2nd time we have tried 2 contact u...   
5568       0              Will Ì_ b going to esplanade fr home?   
5569       0  Pity, * was in mood for that. So...any other s...   
5570       0  The guy did some bitching but I acted like i'd...   
5571       0                         Rofl. Its true to its name   

      num_characters  num_of_words  num_of_sentences  
0                111            24                 2  
1                 29             8                 2  
2                155            37                 2  
3                 49            13                 1  
4                 61            15                 1  
...              ...           ...               ...  
5567             161            35                 4  
5568              37             9                 1  
5569              57            15                 2  
5570             125            27                 1  
5571              26             7                 2  

[5572 rows x 5 columns]

## Text Preprocessing

In [153]:
def transform_text(text):
    text = text.lower()
    text = nltk.word_tokenize(text)
    
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)
    
    text = y[:]
    y.clear()
    
    for i in text:
        if i not in stopwords.words('english'):
            y.append(i)
            
    text = y[:]
    y.clear()
    
    for i in text:
        y.append(ps.stem(i))
    
            
    return " ".join(y)

In [154]:
transform_text("I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.")

'gon na home soon want talk stuff anymor tonight k cri enough today'

In [155]:
data['transformed_text'] = data['text'].apply(transform_text)

In [156]:
data.head()

target                                               text  num_characters  \
0       0  Go until jurong point, crazy.. Available only ...             111   
1       0                      Ok lar... Joking wif u oni...              29   
2       1  Free entry in 2 a wkly comp to win FA Cup fina...             155   
3       0  U dun say so early hor... U c already then say...              49   
4       0  Nah I don't think he goes to usf, he lives aro...              61   

   num_of_words  num_of_sentences  \
0            24                 2   
1             8                 2   
2            37                 2   
3            13                 1   
4            15                 1   

                                    transformed_text  
0  go jurong point crazi avail bugi n great world...  
1                              ok lar joke wif u oni  
2  free entri 2 wkli comp win fa cup final tkt 21...  
3                u dun say earli hor u c alreadi say  
4               nah think goe usf live around though

In [157]:
#from wordcloud import WordCloud 
#wc = WordCloud(width=50, height=50, min_font_size=10, background_color='white')

In [158]:
#wc.generate(data[data['target'] == 1]['transformed_text'].str.cat(sep=""))

## Model Building

In [159]:
## Converting text to numbers

cv = CountVectorizer()
tfidf = TfidfVectorizer(max_features=3000)

In [160]:
X = tfidf.fit_transform(data['transformed_text']).toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [161]:
X.shape

(5572, 3000)

In [162]:
y = data['target'].values

In [163]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [164]:
y.shape

(5572,)

In [165]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [166]:
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

In [167]:
gnb.fit(X_train,y_train)
y_pred1 = gnb.predict(X_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(precision_score(y_test,y_pred1))

0.8672645739910314
[[841 116]
 [ 32 126]]
0.5206611570247934


In [168]:
mnb.fit(X_train,y_train)
y_pred2 = mnb.predict(X_test)
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(precision_score(y_test,y_pred2))

0.9650224215246637
[[956   1]
 [ 38 120]]
0.9917355371900827


In [169]:
bnb.fit(X_train,y_train)
y_pred3 = bnb.predict(X_test)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(precision_score(y_test,y_pred3))


0.9766816143497757
[[955   2]
 [ 24 134]]
0.9852941176470589


In [170]:
pickle.dump(tfidf,open('vectorizer.pkl','wb'))


pickle.dump(mnb,open('model.pkl','wb'))

## Evaluation